### ISSUE TITLE
Safer get or create properties

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel#236]
The offending line: 

https://github.com/pybel/pybel/blob/ba4e01d76438fca738eb65cf3488435329baa7f1/src/pybel/manager/cache_manager.py#L1356

## Questions

- Why isn't this caught during parsing?
- What happens if the URL is unavailable? 
- What happens if the entry is not contained?

## TODO

- [ ] add catcher in `manager._store_graph_parts`
- [ ] reproduce this error in tests
- [ ] add additional validation in the parser itself
